FROM node:18-alpine AS angular-builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build

FROM gradle:jdk21-alpine AS client-builder
WORKDIR /app
COPY client/build.gradle .
COPY client/settings.gradle .
COPY client/gradlew .
COPY client/gradle ./gradle
RUN ./gradlew --no-daemon dependencies
COPY client/src ./src
RUN ./gradlew --no-daemon build

FROM nginx:alpine
COPY --from=angular-builder /app/dist/frontend/browser /usr/share/nginx/html/static/
COPY --from=client-builder /app/build/libs/client-0.0.1-SNAPSHOT.jar /usr/share/nginx/html/client-application.jar
COPY frontend/nginx/nginx.conf /etc/nginx/nginx.conf
COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
