version: '3'

services:
  warmachine:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx

  nginx:
    build:
      context: nginx
    ports:
      - "2224:22"
    depends_on:
      - warmachine
    networks:
      - default
      - nginx

networks:
  nginx:
    internal: true
