version: '3'

services:
  wartank:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx

  nginx:
    build:
      context: nginx
    ports:
      - "2225:22"
    depends_on:
      - wartank
    networks:
      - default
      - nginx

networks:
  nginx:
    internal: true
