version: "3"
services:
  mqtt:
    build:
      context: mqtt
    container_name: mqtt
    restart: unless-stopped
    ports:
      # - 9001:9001
      - 1883:1883

  looper:
    build:
      context: looper
    container_name: looper
    depends_on:
      - mqtt