version: "3"
services:
  mqtt:
    build:
      context: mqtt
    container_name: mqtt
    ports:
      - 1883:1883

  looper:
    build:
      context: looper
    container_name: looper
    depends_on:
      - mqtt