version: '3.8'

services:
  interface_subsystem:
    build:
      context: interface_subsystem
    depends_on:
      - data_subsystem
      - security_subsystem
    networks:
      - nginx

  security_subsystem:
    build:
      context: security_subsystem
    depends_on:
      - data_subsystem
    networks:
      - nginx

  data_subsystem:
    build:
      context: data_subsystem
    environment:
      MYSQL_ROOT_PASSWORD: d8478def08d8
      MYSQL_USER: kestrel
      MYSQL_PASSWORD: 856a0e059c03
      MYSQL_DATABASE: sensors
    networks:
      - nginx

  nginx:
    build:
      context: nginx
    ports:
      - "9085:80"
      - "2235:22"
    depends_on:
      - interface_subsystem
    networks:
      - default
      - nginx

networks:
  nginx:
    internal: true