version: "3"
services:
  app:
    build:
      context: .
    restart: always
    read_only: true
    pids_limit: 2000
    networks:
      - nginx

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - "8000:80"
      - "2222:2222"
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - default
      - nginx

networks:
  nginx:
    internal: true