version: '3.8'

services:
  atlas:
    build: .
    networks:
      - nginx

  nginx:
    build:
      context: nginx
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - atlas
    networks:
      - default
      - nginx

networks:
  nginx:
    internal: true